modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mineflac"
version = "1.0.1-1.21.6"
displayName = "MineFLAC"
authors = "dopadream"
description = '''
The uncompressed soundtrack of Minecraft.
'''
logoFile = "mod_icon.png"

[[dependencies.mineflac]]
modId = "neoforge"
type = "required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mineflac]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mineflac]]
modId = "architectury"
type = "required"
versionRange = "[17.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mineflac.mixins.json"
